name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
workflow_dispatch:
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 -V
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 app.py
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "python"
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Finalizado!"
