name: Flask CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11.6]

  workflow_dispatch:
  
    jobs:
  build-job:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
        python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip3 install flake8 pytest pytest-cov flask
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      security-job:
      run-on: ubuntu-latest
      steps:  
      - name: SAST Test 
        run: python3 app.py
      - uses: AppThreat/sast-scan-action@master
      with:
        type: "python3"
    
      