name: SAST Check

on:
  push:
    branches:
      - main
jobs:
  sast-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'   # Ou a versão desejada do Python

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: |
          bandit -r . -f json -o bandit-report.json

      - name: Upload Reports
        run: |
          mkdir reports
          mv audit-report.json reports/
          mv bandit-report.json reports/
        continue-on-error: true

      - name: Push Reports to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: sast-reports
          path: reports
