name: SAST and DAST Check

on:
  push:
    branches:
      - main

jobs:
  sast-and-dast-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Ou a versão desejada do Python

      - name: Bandit Scan
        uses: shundor/python-bandit-scan@v1.0
            
      - name: Run Bandit (SAST)
        run: |
          bandit -r . -f json -o bandit-report.json
        continue-on-error: true

      - name: Upload Reports
        run: |
          mkdir reports
          mv bandit-report.json reports/
          mv ZAPReport.html reports/
        continue-on-error: true

      - name: Push Reports to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: sast-dast-reports
          path: reports
